services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: flyaway-db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong!Passw0rd"
    ports:
      - "1433:1433"
    volumes:
      - flyaway_sql_data:/var/opt/mssql

  web:
    build:
      context: .
      dockerfile: Fly-Away/Dockerfile
    container_name: flyaway-web
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_URLS: "http://+:8080"
      ASPNETCORE_ENVIRONMENT: "Production"
      ConnectionStrings__DefaultConnection: "Server=db,1433;Database=FlyAwayDb;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;"
      SEED_DATA: "true"
    depends_on:
      - db

volumes:
  flyaway_sql_data: